//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessOnlineWebApp.AuthorizationServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthorizationServiceReference.IAuthorizationService")]
    public interface IAuthorizationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizationService/AuthorizeUser", ReplyAction="http://tempuri.org/IAuthorizationService/AuthorizeUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ChessOnlineWebAPI.AuthorizationServiceReference.AuthorizationFault), Action="http://tempuri.org/IAuthorizationService/AuthorizeUserAuthorizationFaultFault", Name="AuthorizationFault", Namespace="http://schemas.datacontract.org/2004/07/AuthorizationService")]
        ChessOnlineWebAPI.AuthorizationServiceReference.User AuthorizeUser(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizationService/AuthorizeUser", ReplyAction="http://tempuri.org/IAuthorizationService/AuthorizeUserResponse")]
        System.Threading.Tasks.Task<ChessOnlineWebAPI.AuthorizationServiceReference.User> AuthorizeUserAsync(string token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthorizationServiceChannel : ChessOnlineWebApp.AuthorizationServiceReference.IAuthorizationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthorizationServiceClient : System.ServiceModel.ClientBase<ChessOnlineWebApp.AuthorizationServiceReference.IAuthorizationService>, ChessOnlineWebApp.AuthorizationServiceReference.IAuthorizationService {
        
        public AuthorizationServiceClient() {
        }
        
        public AuthorizationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthorizationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorizationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorizationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ChessOnlineWebAPI.AuthorizationServiceReference.User AuthorizeUser(string token) {
            return base.Channel.AuthorizeUser(token);
        }
        
        public System.Threading.Tasks.Task<ChessOnlineWebAPI.AuthorizationServiceReference.User> AuthorizeUserAsync(string token) {
            return base.Channel.AuthorizeUserAsync(token);
        }
    }
}
